# Generated by Django 4.2.11 on 2026-08-09 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def seed_report_timelines(apps, schema_editor):
    Report = apps.get_model('myapp', 'Report')
    ReportForward = apps.get_model('myapp', 'ReportForward')
    ReportForwardToadmin = apps.get_model('myapp', 'ReportForwardToadmin')
    ReportTimeline = apps.get_model('myapp', 'ReportTimeline')

    for report in Report.objects.all().iterator():
        submitted = ReportTimeline.objects.create(
            report_id=report.pk,
            action='submit',
            from_status='submitted',
            to_status='submitted',
            from_level='street',
            to_level='street',
            performed_by_id=report.user_id,
            performed_by_role='user' if report.user_id else '',
            public_comment='Your report was submitted and sent to the street office.',
        )
        ReportTimeline.objects.filter(pk=submitted.pk).update(created_at=report.created_at)

        current_status = 'submitted'
        current_level = 'street'
        assigned_to_id = None
        street_forward = ReportForward.objects.filter(report_id=report.pk).order_by('forwarded_at').first()
        if street_forward:
            event = ReportTimeline.objects.create(
                report_id=report.pk,
                action='forward_to_ward',
                from_status=current_status,
                to_status='forwarded_to_ward',
                from_level=current_level,
                to_level='ward',
                performed_by_id=street_forward.from_user_id,
                performed_by_role='village_chairman',
                public_comment='Your report was forwarded to the ward office.',
            )
            ReportTimeline.objects.filter(pk=event.pk).update(created_at=street_forward.forwarded_at)
            current_status = 'forwarded_to_ward'
            current_level = 'ward'
            assigned_to_id = street_forward.to_user_id

        municipal_forward = ReportForwardToadmin.objects.filter(report_id=report.pk).order_by('forwarded_at').first()
        if municipal_forward:
            event = ReportTimeline.objects.create(
                report_id=report.pk,
                action='forward_to_municipal',
                from_status=current_status,
                to_status='forwarded_to_municipal',
                from_level=current_level,
                to_level='municipal',
                performed_by_id=municipal_forward.from_user_id,
                performed_by_role='ward_executive',
                public_comment='Your report was forwarded to the municipal office.',
            )
            ReportTimeline.objects.filter(pk=event.pk).update(created_at=municipal_forward.forwarded_at)
            current_status = 'forwarded_to_municipal'
            current_level = 'municipal'
            assigned_to_id = municipal_forward.to_user_id

        Report.objects.filter(pk=report.pk).update(
            status=current_status,
            current_level=current_level,
            assigned_to_id=assigned_to_id,
        )


def remove_seeded_report_timelines(apps, schema_editor):
    apps.get_model('myapp', 'ReportTimeline').objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_openspace_boundary_shape_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='current_level',
            field=models.CharField(choices=[('street', 'Street office'), ('ward', 'Ward office'), ('municipal', 'Municipal office'), ('completed', 'Completed')], db_index=True, default='street', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('clarification_requested', 'Clarification requested'), ('verified', 'Verified'), ('forwarded_to_ward', 'Forwarded to ward'), ('forwarded_to_municipal', 'Forwarded to municipal'), ('in_progress', 'Work in progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], db_index=True, default='submitted', max_length=32),
        ),
        migrations.AddField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('staff', 'Staff'), ('ward_executive', 'Ward Executive'), ('village_chairman', 'Village Chairman'), ('municipal_officer', 'Municipal Officer'), ('user', 'User')], default='user', max_length=20),
        ),
        migrations.CreateModel(
            name='ReportTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', 'Submitted'), ('accept', 'Accepted for review'), ('request_clarification', 'Clarification requested'), ('add_note', 'Progress note added'), ('verify', 'Verified'), ('forward_to_ward', 'Forwarded to ward'), ('forward_to_municipal', 'Forwarded to municipal'), ('start_work', 'Work started'), ('resolve', 'Resolved'), ('close', 'Closed'), ('reject', 'Rejected')], max_length=32)),
                ('from_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('clarification_requested', 'Clarification requested'), ('verified', 'Verified'), ('forwarded_to_ward', 'Forwarded to ward'), ('forwarded_to_municipal', 'Forwarded to municipal'), ('in_progress', 'Work in progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=32)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('clarification_requested', 'Clarification requested'), ('verified', 'Verified'), ('forwarded_to_ward', 'Forwarded to ward'), ('forwarded_to_municipal', 'Forwarded to municipal'), ('in_progress', 'Work in progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], max_length=32)),
                ('from_level', models.CharField(choices=[('street', 'Street office'), ('ward', 'Ward office'), ('municipal', 'Municipal office'), ('completed', 'Completed')], max_length=20)),
                ('to_level', models.CharField(choices=[('street', 'Street office'), ('ward', 'Ward office'), ('municipal', 'Municipal office'), ('completed', 'Completed')], max_length=20)),
                ('performed_by_role', models.CharField(blank=True, max_length=32)),
                ('public_comment', models.TextField(blank=True)),
                ('internal_comment', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_timeline_actions', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='myapp.report')),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['report', 'created_at'], name='myapp_repor_report__9f0988_idx')],
            },
        ),
        migrations.RunPython(seed_report_timelines, remove_seeded_report_timelines),
    ]
